stations = {
    # 'Station Id': ['Station City Name', 'State/Province Abrv', State/Province Name']
    # ----------- UNITED STATES ----------
    #-- GREAT LAKES-----------------------
    'DTX': ["Detroit / White Lake", "MI", "Michigan"],
    'APX': ["Gaylord", "MI", "Michigan"],
    'GRB': ["Green Bay", "WI", 'Wisconsin'],
    'MPX': ["Twin Cities", "MN", 'Minnesota'],
    'INL': ["International Falls", "MN", 'Minnesota'],
    'DVN': ["Davenport", "IA", "Iowa"],
    'ILX': ["Lincoln", "IL", "Illinois"],
    'ILN': ["Wilmington", "OH", "Ohio"],
    #-- NORTHEAST ----------------------
    'PIT': ["Pittsburgh", "PA", "Pennsylvania"],
    'BUF': ["Buffalo", "NY", "New York"],
    'ALB': ["Albany", "NY", "New York"],
    'GYX': ["Gray", "ME", "Maine"],
    'CAR': ["Caribou", "ME", "Maine"],
    #--- THE SOUTH ---------------------
    'IAD': ["Sterling", "VA", "Virginia"],
    'WAL': ["Wallops Island", "VA", "Virginia"],
    'RNK': ["Blacksburg", "VA", "Virginia"],
    'GSO': ["Greensboro", "NC", "North Carolina"],
    'MHX': ["Newport", "NC", "North Carolina"],
    'CHS': ["Charleston", "SC", "South Carolina"], 
    'BNA': ["Nashville", "TN", "Tennessee"],
    'FFC': ["Peachtree City", "GA", "Georgia"],
    'BMX': ["Shelby County Airport", "AL", "Alabama"],
    'JAX': ["Jacksonville", "FL", "Florida"],
    'TLH': ["Tallahassee", "FL", "Florida"],
    'TBW': ["Tampa Bay", "FL", "Florida"],
    'MFL': ["Miami", "FL", "Florida"],
    'KEY': ["Key West", "FL", "Florida"],
    'LIX': ["Slidell Muni", "LA", "Louisiana"],
    'LCH': ["Lake Charles", "LA", "Louisiana"],
    'SHV': ["Shreveport", "LA", "Louisiana"],
    'JAN': ["Jackson Thompson Fld", "MS", "Mississippi"],
    'LZK': ["Little Rock", "AR", "Arkansas"], 
    #-- SOUTHERN PLAINS ------------------
    'SGF': ["Springfield", "MO", "Missouri"],
    'CRP': ["Corpus Christi", "TX", "Texas"],
    'FWD': ["Dallas/FW", "TX", "Texas"],
    'DRT': ["Del Rio", "TX", "Texas"],
    'MAF': ["Midland", "TX", "Texas"],
    'BRO': ["Brownsville", "TX", "Texas"],
    'EPZ': ["Santa Teresa", "TX",  "Texas"],
    'AMA': ["Amarillo", "TX", "Texas"],
    'OUN': ["Norman", "OK", "Oklahoma"],
    'LMN': ["Lamont", "OK", "Oklahoma"],
    'DDC': ["Dodge City", "KS", "Kansas"],
    'TOP': ["Topeka", "KS", "Kansas"],
    #-- NORTHERN & HIGH PLAINS ------------
    'LBF': ["North Platte", "NE", "Nebraska"],
    'OAX': ["Omaha", "NE", "Nebraska"],
    'RAP': ["Rapid City", "SD", "South Dakota"],
    'ABR': ["Aberdeen", "SD", "South Dakota"],
    'BIS': ["Bismarck", "ND", "North Dakota"],
    'TFX': ["Great Falls", "MT", "Montana"],
    'RIW': ["Riverton", "WY", "Wyoming"],
    'DNR': ["Denver", "CO", "Colorado"],
    #-- ROCKIES AND NORTHWEST -------------
    'OTX': ["Spokane", "WA", "Washington"],
    'UIL': ["Quillayute", "WA", "Washington"],
    'SLE': ["Salem", "OR", "Oregon"],
    'MFR': ["Medford", "OR", "Oregon"],
    'BOI': ["Boise", "ID", "Idaho"],
    'LKN': ["Elko", "NV", "Nevada"],
    'SLC': ["Salt Lake City", "NV", "Nevada"],
    'GJT': ["Grand Juction", "CO", "Colorado"],
    #-- SOUTHWEST ------------------------
    'REV': ["Reno", "NV", "Nevada"],
    'VEF': ["Las Vegas", "NV", "Nevada"],
    'FGZ': ["Flagstaff", "AZ", "Arizona"],
    'TUS': ["Tucson", "AZ", "Arizona"],
    'ABQ': ["Albuquerque", "NM", "New Mexico"],
    'NKX': ["San Diego", "CA", "California"],
    'VBG': ["Vandenberg AFB", "CA", "California"],
    'OAK': ["Oakland", "CA", "California"],
    #-- ALASKA ---------------------------
    'PANT': ["Annette Island", "AK", "Alaska"],
    'PAYA': ["Yakutat", "AK", "Alaska"],
    'PADQ': ["Kodiak", "AK", "Alaska"],
    'PACD': ["Cold Bay", "AK", "Alaska"],
    'PASY': ["Shemya AFB", "AK", "Alaska"],
    'PASN': ["St. Paul", "AK", "Alaska"],
    'PAKN': ["King Salmon", "AK", "Alaska"],
    'PANC': ["Anchorage", "AK", "Alaska"],
    'PABE': ["Bethel", "AK", "Alaska"],
    'PAMC': ["Mcgrath", "AK", "Alaska"],
    'PAFA': ["Fairbanks", "AK", "Alaska"],
    'PAOM': ["Nome", "AK", "Alaska"],
    'PAOT': ["Kotzebue, Ralph Wien", "AK", "Alaska"],
    'PABR': ["Barrow", "AK", "Alaska"],
    #-------------- CANADA ---------------
    #--Nova Scotia ----------------------
    'YQI': ["Yarmouth", "NS", "Nova Soctia"],
    'AWE': ["Shearwater", "NS", "Nova Soctia"],
    #--Newfoundland ---------------------
    'YYR': ["Goose Bay", "NF", "Newfoundland"],
    'YJT': ["Stephenville", "NF", "Newfoundland"],
    'AYT': ["Mt Pearl", "NF", "Newfoundland"],
    #--Quebec --------------------------
    'WPH': ["Inukjuak", "QB", "Quebec"],
    'YVP': ["Kuujjuaq", "QB", "Quebec"],
    'WMW': ["Maniwaki", "QB", "Quebec"],
    'YAH': ["La Grande Iv", "QB", "Quebec"],
    'YZV': ["Sept-Iles", "QB", "Quebec"],
    #--Ontario -------------------------
    'YMO': ["Moosonee", "ON", "Ontario"],
    'WPL': ["Pickle Lake", "ON", "Ontario"],
    #--Manitoba ------------------------    
    'YYQ': ["Churchill", "MB", "Manitoba"],
    'YQD': ["The Pas", "MB", "Manitoba"],
    #--Alberta -------------------------
    'WSE': ["Edmonton Stony Plain", "AB", "Alberta"],
    #--British Columbia ---------------
    'CWVK': ["Vernon", "BC", "British Columbia"],
    'ZXS': ["Prince George", "BC", "British Columbia"],
    'YYE': ["Fort Nelson", "BC", "British Columbia"],
    'YZT': ["Port Hardy", "BC", "British Columbia"],
    #--Yukon --------------------------
    'YXY': ["Whitehorse", "YT", "Yukon"],
    #--Northwest Territories ----------
    'YVQ': ["Norman Wells Ua", "NT", "Northwest Territories"],
    'YEV': ["Inuvik", "NT", "Northwest Territories"],
    'YBK': ["Baker Lake", "NT", "Northwest Territories"],
    'YCB': ["Cambridge Bay", "NT", "Northwest Territories"],
    'YUX': ["Hall Beach", "NT", "Northerst Territories"],
    'YFB': ["Iqaluit", "NT", "Northerst Territories"],
    #-- ATLANTIC ISLANDS------------------
    'TJSJ': ["San Juan", "PR", "Puerto Rico"],
    'MDSD': ["Santo Domingo", "DO", "Dominican Republic"]
    
}
