stations = {
    #------------------------------------ GREAT LAKES
    'DTX': "Detroit / White Lake, MI",
    'APX': "Gaylord, MI",
    'GRB': "Green Bay, WI",
    'MPX': "Twin Cities, MN",
    'INL': "International Falls, MN",
    'DVN': "Davenport, IA",
    'ILX': "Lincoln, IL",
    'ILN': "Wilmington, OH",
    #------------------------------------ NORTHEAST
    'PIT': "Pittsburgh, PA",
    'BUF': "Buffalo, NY",
    'ALB': "Albany, NY",
    'GYX': "Gray, ME",
    'CAR': "Caribou, ME",
    'YQI': "Yarmouth, NS",
    'IAD': "Sterling, VA",
    #------------------------------------ THE SOUTH
    'WAL': "Wallops Island, VA",
    'RNK': "Blacksburg, VA",
    'GSO': "Greensboro, NC",
    'MHX': "Newport, NC",
    'BNA': "Nashville, TN",
    'FFC': "Peachtree City, GA",
    'BMX': "Shelby County Airport, AL",
    'JAX': "Jacksonville, FL",
    'TLH': "Tallahassee, FL",
    'TBW': "Tampa Bay, FL",
    'MFL': "Miami, FL",
    'KEY': "Key West, FL",
    'LIX': "Slidell Muni, LA",
    'LCH': "Lake Charles, LA",
    'JAN': "Jackson Thompson Fld, MS",
    'SHV': "Shreveport, LA",
    'LZK': "Little Rock, AR",
    'CHS': "Charleston, SC",  
    #------------------------------------ SOUTHERN PLAINS 
    'SGF': "Springfield, MO",
    'CRP': "Corpus Christi, TX",
    'FWD': "Dallas/FW, TX",
    'DRT': "Del Rio, TX",
    'MAF': "Midland, TX",
    'BRO': "Brownsville, TX",
    'EPZ': "Santa Teresa, TX",
    'AMA': "Amarillo, TX",
    'OUN': "Norman, OK",
    'LMN': "Lamont, OK",
    'DDC': "Dodge City, KS",
    'TOP': "Topeka, KS",
    #------------------------------------ NORTHERN & HIGH PLAINS 
    'LBF': "North Platte, NE",
    'OAX': "Omaha, NE",
    'RAP': "Rapid City, SD",
    'ABR': "Aberdeen, SD",
    'BIS': "Bismarck, ND",
    'TFX': "Great Falls, MT",
    'RIW': "Riverton, WY",
    'DNR': "Denver, CO",
    #------------------------------------ ROCKIES AND NORTHWEST 
    'OTX': "Spokane, WA",
    'UIL': "Quillayute, WA",
    'SLE': "Salem, OR",
    'BOI': "Boise, ID",
    'MFR': "Medford, OR",
    'LKN': "Elko, NV",
    'SLC': "Salt Lake City, NV",
    'GJT': "Grand Juction, CO",
    #------------------------------------ SOUTHWEST
    'REV': "Reno, NV",
    'VEF': "Las Vegas, NV",
    'FGZ': "Flagstaff, AZ",
    'ABQ': "Albuquerque, NM",
    'TUS': "Tucson, AZ",
    'NKX': "San Diego, CA",
    'VBG': "Vandenberg AFB, CA",
    'OAK': "Oakland, CA"
}
